tmgmt.translator.settings.smartling:
  type: mapping
  mapping:
    api_url:
      type: string
      label: 'API URL'
    project_id:
      type: string
      label: 'Project ID'
    key:
      type: string
      label: 'Key'
    export_format:
      type: string
      label: Default export format

